version: '3'
services:
  my-python-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-python-app-image
    container_name: my-python-app-container
    environment:
      - IN_DOCKER=True
    ports:
      - "6006:6006"  
    volumes:
      - ./app:/app 
    restart: always
