version: '3'
services:
  rl-trade-bot-torch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl-trade-bot-torch-demo
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data:/app/data
    env_file:
      - docker.env
    restart: always

